dist: xenial
language: generic

services:
  - docker

matrix:
  # Lets build be marked complete if all required matrix is finished
  # https://docs.travis-ci.com/user/build-matrix/#fast-finishing
  fast_finish: true

  include:
  # Docker w/ framework
  - os: linux
    env: TYPE="docker"
    sudo: required

  # Conda w/o mantid-framework
  - os: linux
    env: TYPE="conda" CONDA=2.7    PKG="mantid-total-scattering-python-wrapper"
    sudo: required
  - os: linux
    env: TYPE="conda" CONDA=3.6    PKG="mantid-total-scattering-python-wrapper"
    sudo: required

  # Conda w/ mantid-framework
  - os: linux
    env: TYPE="conda" CONDA=2.7 PKG="mantid-total-scattering"
    sudo: required
  - os: linux
    env: TYPE="conda" CONDA=3.6    PKG="mantid-total-scattering"
    sudo: required

  # Since Mantid Framework is prone to seg faults
  allow_failures:
    - os: linux
      env: TYPE="conda" CONDA=2.7 PKG="mantid-total-scattering"
      sudo: required
    - os: linux
      env: TYPE="conda" CONDA=3.6    PKG="mantid-total-scattering"
      sudo: required

before_install:
  - | 
    if [[ "${TYPE}" == "docker" ]]; then
      docker build -t test-env -f .ci/Dockerfile.nightly_ubuntu16.04_python3 .;
      test_cmd=`./.ci/construct_test_command.sh`;
    fi

  - |
    if [[ "${TYPE}" == "conda" ]]; then
      MINICONDA_URL="https://repo.continuum.io/miniconda";
      MINICONDA_FILE="Miniconda${CONDA:0:1}-latest-Linux-x86_64.sh";
      wget "${MINICONDA_URL}/${MINICONDA_FILE}";
      bash ${MINICONDA_FILE} -b -p $HOME/miniconda;
      export PATH="$HOME/miniconda/bin:$PATH";

      sudo apt-get install freeglut3-dev libglu1-mesa;
    fi


install:
  - |
    if [[ "${TYPE}" == "conda" ]]; then
      conda config --set always_yes yes --set changeps1 no --set anaconda_upload no;
      conda config --add channels conda-forge --add channels mantid;
      # conda update  -q conda
      # pinned because 4.7.7 is broken when using `conda update -q conda`
      # can remove this if this issue is closed:
      # - https://github.com/conda/conda/issues/8934
      conda install  -q conda==4.7.5;
      conda info -a

      conda create -q -n ${PKG} python=$CONDA flake8 conda-build=3.17 conda-verify anaconda-client pytest;
      source activate ${PKG}

      # Build recipe and install 
      PKG_PATH="./conda.recipe/${PKG}"
      conda build ${PKG_PATH}
      export PKG_FILE=$(conda build ${PKG_PATH} --output)
      conda install ${PKG_FILE}
      
    fi

script:
  - |
    if [[ "${TYPE}" == "docker" ]]; then
      docker run -t test-env /bin/bash -c "$test_cmd";
      sudo python setup.py install;
    fi

  - |
    if [[ "${TYPE}" == "conda" ]]; then
      conda install -c mantid/label/nightly mantid-framework=4
      python setup.py test;
    fi

deploy:

 # Deploy pure-python package to PyPI https://pypi.org/project/mantid-total-scattering/
 - provider: pypi
   user: mcdonnellmt
   skip_cleanup: true
   skip_existing: true
   on:
     tags: true
     branch: master
   password:
     secure: kqA6ITb6fr+9Q/KBeU/mxa+d319Uwgc9wi8OPsZssvSneQ8vGAIVSSDBeCVbKSXLjXUIKUWYfndOiqT8wCQU+jpY1TZG0Bm0zWGGxBvcUJEnVrB7siWJ6l+MZ4nPXFFMtwhP0KMDtwen0fLnGOLQlNLyz3qb0Lf8NkM1BumXDK7Lc7p/x8ziKHQothL047jx+0PMsydbTdK2gae/ADm6R4z+ZJirv0/yciUQnCwmiXSnYX5UHtkXqP3k21ZtTV3eA9vNvK1HMEti51lFDrgTt5EBOxtX0UIz6YqfCl5ZHyXMS4uCwqL/m7gRPAc1MTmSurZ4JJkvsaVrU3vUdIimlm2EwqH6+yOfjvWlTdwjglkplt4Z95/rN3CLvYIrYq76XsG2yxY8c11+xmpSMo2/6vbRvmKhmbyV6tFeBgq5rflA/xJkM5WqSyMcE0lhk8xc0RL7aAeblyAs9q/hN9BiZIesegE6pd8DWYEGw6cWnwzaflLgze0nJYE5gQ5z5LZJky8/Nxdxumtf9XVS48PenaNIbDLLG1ER2nufHHg3/5Yv+c0TMRWKv6plb4OLj2AIYa2aSedm7YyVhCbVV0/xM0HxZ8fpKxBMDuFuuU1S1YgQkex7cCfj2QW2JBGoX/iAvPz1sZcU7A+VKaKMJyY+SSmQf+Sz3Px3O8CE+9LerV4=

 # Deploy conda package to Anaconda.org https://anaconda.org/marshallmcdonnell/mantid-total-scattering
 - provider: script
   script: cd conda.recipe && chmod +x anaconda_upload.sh && ./anaconda_upload.sh ${PKG_FILE}
   skip_cleanup: true
   skip_existing: true
   on:
     branch: master
     tags: true
     condition: $TYPE = conda
